services:
  db:
    image: postgres:16-alpine
    ports:
      - 5433:5432
    volumes:
      - ".:/docker-entrypoint-initdb.d"
    environment:
      POSTGRES_USER: praktikum
      POSTGRES_PASSWORD: labdas
      POSTGRES_DB: bioskop